package Step9.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_SIGNAL extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SIGNAL() {
    super(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f129661L, "SIGNAL", "r:88da3f3a-8ab9-4597-b28b-094b22c9fab5(Step9.structure)/2775757920452908641", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_HIGH_0 = new EnumerationDescriptor.MemberDescriptor("HIGH", "high", "r:88da3f3a-8ab9-4597-b28b-094b22c9fab5(Step9.structure)/2775757920452908642", "HIGH");
  private final EnumerationDescriptor.MemberDescriptor VALUE_LOW_0 = new EnumerationDescriptor.MemberDescriptor("LOW", "low", "r:88da3f3a-8ab9-4597-b28b-094b22c9fab5(Step9.structure)/2775757920452908643", "LOW");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_HIGH_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_HIGH_0, VALUE_LOW_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "HIGH":
        return VALUE_HIGH_0;
      case "LOW":
        return VALUE_LOW_0;
    }
    return null;
  }
}
