package ArduinoML.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Action_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Actuator_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new App_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new ConditionRef_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Sensor_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new SensorCondition_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new State_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new Timer_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new TimerCondition_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new Transition_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new Action_SubstituteMenu());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new App_SubstituteMenu());
      case 2:
        return Collections.<SubstituteMenu>singletonList(new ConditionRef_SubstituteMenu());
      case 3:
        return Collections.<SubstituteMenu>singletonList(new SensorCondition_SubstituteMenu());
      case 4:
        return Collections.<SubstituteMenu>singletonList(new TimerCondition_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f12965cL), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f12964fL), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f129644L), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x317184a93da45e98L), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f25d4eeL), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f25db8aL), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f129654L), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f25db98L), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f25db9bL), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f25dba0L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f12965cL), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f129644L), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x317184a93da45e98L), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f25db8aL), MetaIdFactory.conceptId(0x662d4de51c934765L, 0x9ae156648221cb83L, 0x2685791f3f25db9bL)).seal();
}
