package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int Actuator = 1;
  public static final int App = 2;
  public static final int Condition = 3;
  public static final int ConditionRef = 4;
  public static final int ConditionReference = 5;
  public static final int Sensor = 6;
  public static final int SensorCondition = 7;
  public static final int SevenSegment = 8;
  public static final int State = 9;
  public static final int Timer = 10;
  public static final int TimerCondition = 11;
  public static final int Transition = 12;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x662d4de51c934765L, 0x9ae156648221cb83L);
    builder.put(0x2685791f3f12965cL, Action);
    builder.put(0x2685791f3f12964fL, Actuator);
    builder.put(0x2685791f3f129644L, App);
    builder.put(0x2685791f3f25d4edL, Condition);
    builder.put(0x317184a93da45e98L, ConditionRef);
    builder.put(0x455c5f479fe4c639L, ConditionReference);
    builder.put(0x2685791f3f25d4eeL, Sensor);
    builder.put(0x2685791f3f25db8aL, SensorCondition);
    builder.put(0x455c5f479fe4c550L, SevenSegment);
    builder.put(0x2685791f3f129654L, State);
    builder.put(0x2685791f3f25db98L, Timer);
    builder.put(0x2685791f3f25db9bL, TimerCondition);
    builder.put(0x2685791f3f25dba0L, Transition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
